In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

In [90]:
from lasagne import layers
from lasagne.updates import nesterov_momentum
from nolearn.lasagne import NeuralNet
from lasagne.nonlinearities import softmax

In [4]:
from utils import load

In [5]:
X_train, X_test, y_train, y_test = load.get_train_test_split()

In [6]:
in_size = X_train.shape[1]
out_size = y_train.max() + 1

In [118]:
net1 = NeuralNet(
    layers=[  # three layers: one hidden layer
        ('input', layers.InputLayer),
        ('hidden', layers.DenseLayer),
#         ('dropout1', layers.DropoutLayer),
        ('hidden2', layers.DenseLayer),
        ('output', layers.DenseLayer),
        ],
    # layer parameters:
    input_shape=(None, in_size),

    hidden_num_units=128,
    hidden2_num_units=50,
#     dropout1_p=0.1,
    output_nonlinearity=softmax,  # output layer uses identity function
    output_num_units=out_size,

    # optimization method:
    update=nesterov_momentum,
    update_learning_rate=0.0001,
#     update_momentum=0.1,

    max_epochs=5000,  # we want to train this many epochs
    verbose=1,
    )

In [ ]:
net1.fit(X_train, y_train.astype(np.int32))

  input             	(None, 93)          	produces      93 outputs
  hidden            	(None, 128)         	produces     128 outputs
  hidden2           	(None, 50)          	produces      50 outputs
  output            	(None, 9)           	produces       9 outputs

 Epoch  |  Train loss  |  Valid loss  |  Train / Val  |  Valid acc  |  Dur
--------|--------------|--------------|---------------|-------------|-------
     1  |    1.961896  |    1.575114  |     1.245558  |     52.28%  |  0.2s
     2  |    1.439009  |    1.346552  |     1.068662  |     61.35%  |  0.2s
     3  |    1.268573  |    1.217208  |     1.042199  |     64.51%  |  0.2s
     4  |    1.161824  |    1.127379  |     1.030553  |     66.62%  |  0.2s
     5  |    1.085841  |    1.061008  |     1.023406  |     67.95%  |  0.2s
     6  |    1.029195  |    1.010440  |     1.018561  |     69.00%  |  0.2s
     7  |    0.985432  |    0.970921  |     1.014945  |     69.67%  |  0.2s
     8  |    0.950716  |    0.939309  |     1.0

In [97]:
y_pred = net1.predict(X_test)

In [98]:
y_pred

array([5, 1, 5, ..., 5, 2, 7])

In [99]:
from sklearn.metrics import accuracy_score

In [100]:
accuracy_score(y_pred, y_test)

0.76253672869735556

## train all

In [101]:
X, y = load.get_train()

In [103]:
net1.fit(X, y.astype(np.int32))


 Epoch  |  Train loss  |  Valid loss  |  Train / Val  |  Valid acc  |  Dur
--------|--------------|--------------|---------------|-------------|-------
     1  |    0.602079  |    1.004333  |     0.599482  |     63.74%  |  0.2s
     2  |    0.678213  |    1.031214  |     0.657684  |     63.44%  |  0.2s
     3  |    0.684386  |    1.021748  |     0.669819  |     63.92%  |  0.2s
     4  |    0.685230  |    1.010943  |     0.677813  |     64.33%  |  0.2s
     5  |    0.685394  |    1.000013  |     0.685385  |     64.60%  |  0.2s
     6  |    0.685286  |    0.989378  |     0.692644  |     64.72%  |  0.2s
     7  |    0.685040  |    0.979146  |     0.699630  |     64.98%  |  0.2s
     8  |    0.684755  |    0.969457  |     0.706329  |     65.25%  |  0.2s
     9  |    0.684449  |    0.960089  |     0.712901  |     65.51%  |  0.2s
    10  |    0.684116  |    0.951089  |     0.719297  |     65.79%  |  0.2s
    11  |    0.683717  |    0.942497  |     0.725432  |     66.09%  |  0.2s
    12  |  

NeuralNet(X_tensor_type=<function matrix at 0x108be4ed8>,
     batch_iterator_test=<nolearn.lasagne.BatchIterator object at 0x109a53410>,
     batch_iterator_train=<nolearn.lasagne.BatchIterator object at 0x109a533d0>,
     eval_size=0.2, hidden_num_units=128, input_shape=(None, 93),
     layers=[('input', <class 'lasagne.layers.input.InputLayer'>), ('hidden', <class 'lasagne.layers.dense.DenseLayer'>), ('output', <class 'lasagne.layers.dense.DenseLayer'>)],
     loss=None, max_epochs=100, more_params={},
     objective=<class 'lasagne.objectives.Objective'>,
     objective_loss_function=<function categorical_crossentropy at 0x108dca488>,
     on_epoch_finished=(), on_training_finished=(),
     output_nonlinearity=<function softmax at 0x105fa4140>,
     output_num_units=9, regression=False,
     update=<function nesterov_momentum at 0x1097ca500>,
     update_learning_rate=0.0001, use_label_encoder=False, verbose=1,
     y_tensor_type=TensorType(int32, vector))

In [104]:
X_test = load.get_test()

In [105]:
y_pred = net1.predict_proba(X_test)

In [106]:
y_pred

array([[  1.19579721e-05,   7.58083257e-02,   4.54866027e-01, ...,
          1.77164021e-02,   8.71776649e-06,   2.05714055e-05],
       [  2.99845573e-03,   3.78092073e-04,   8.47790796e-05, ...,
          1.18507158e-04,   4.08724243e-01,   1.73258540e-03],
       [  2.24824154e-07,   8.04547203e-08,   8.60460097e-09, ...,
          8.05620728e-06,   3.35199202e-05,   3.21060934e-06],
       ..., 
       [  2.09205920e-07,   5.60069365e-02,   7.51657125e-01, ...,
          3.16162849e-03,   5.09827752e-06,   4.47464172e-07],
       [  4.98719393e-05,   2.99525205e-01,   3.68194208e-01, ...,
          1.78026568e-03,   1.50806001e-04,   1.76497936e-04],
       [  1.47759324e-03,   2.30405569e-01,   3.73946218e-01, ...,
          1.83928706e-01,   9.73016344e-04,   1.63789204e-03]])

In [107]:
y_pred.sum(axis=1)

array([ 1.,  1.,  1., ...,  1.,  1.,  1.])

In [108]:
load.gen_submission('lasagne_h1_100ep', y_pred)